Lab5_todo/lab5/auth_/urls.py
from rest_framework_jwt.views import obtain_jwt_token
from django.urls import path

urlpatterns = [
    path('', obtain_jwt_token),
]

Lab5_todo/lab5/lab5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', include('auth_.urls'))
]

Lab5_todo/lab5/main/urls.py
from django.urls import path
from main.views import TodoListViewSet, TodoViewSet, CompletedTodoViewSet

urlpatterns = [
    path('todos', TodoViewSet.as_view({'get': 'list'})),
    path('todos/<int:pk>', TodoListViewSet.as_view({'get': 'retrieve'})),
    path('todos/<int:pk>/completed', CompletedTodoViewSet.as_view({'get': 'retrieve'})),
]

Lab5_todo/lab5/auth_/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _


class User(AbstractBaseUser):
    email = models.EmailField(_('email address'), unique=True)
    name = models.CharField(_('name'), max_length=30, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['email', 'name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

Lab5_todo/lab5/main/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = 'Список'
        verbose_name_plural = 'Списки'

    def __str__(self):
        return self.name


class Todo(models.Model):
    name = models.CharField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)
    due_on_date = models.DateTimeField()
    owner = models.CharField(max_length=100)
    list_id = models.ForeignKey(TodoList, on_delete=models.RESTRICT, related_name='todos')
    category = models.CharField(max_length=40, default='Incomplete')

    class Meta:
        ordering = ['id']
        verbose_name = 'Дело'
        verbose_name_plural = 'Дела'

    def __str__(self):
        return self.name

Lab5_todo/lab5/auth_/views.py
from django.shortcuts import render

# Create your views here.

Lab5_todo/lab5/main/views.py
from django.http import Http404
from rest_framework import status, viewsets
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from .serializers import TodoListModelSerializer, TodoModelSerializer, TodoSerializer, TodoListSerializer
from .models import Todo, TodoList


# def login(request):
#     username = request.POST('username')
#     password = request.POST('password')
#     user = auth.authenticate(username=username, password=password)
#     if user is not None and user.is_active:
#         auth.login(request, user)
#         return HttpResponseRedirect("/todos")
#     else:
#         return HttpResponseRedirect("/")


class TodoListViewSet(viewsets.ViewSet):
    permission_classes = (IsAuthenticated,)

    def list(self, request):
        queryset = TodoList.objects.all()
        serializer = TodoListModelSerializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk=None):
        queryset = TodoList.objects.all()
        user = get_object_or_404(queryset, pk=pk)
        serializer = TodoListSerializer(user)
        return Response(serializer.data)

    def create(self, request):
        todoList_data = request.data
        new_todoList = TodoList.objects.create(name=todoList_data['name'])
        new_todoList.save()
        serializer = TodoListModelSerializer(new_todoList)
        return Response(serializer.data)

    def destroy(self, request):
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            pass
        return Response(status=status.HTTP_204_NO_CONTENT)

    def update(self, request):
        print(request.data['result'])


class TodoViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    serializer_class = TodoModelSerializer
    queryset = Todo.objects.all()


class CompletedTodoViewSet(viewsets.ViewSet):
    permission_classes = (IsAuthenticated,)

    def list(self, request):
        queryset = Todo.objects.filter(category='Completed')
        serializer = TodoSerializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk=None):
        todos = Todo.objects.filter(category='Completed', list_id=pk)
        serializer = TodoModelSerializer(todos, many=True)
        return Response(serializer.data)

    def create(self, request):
        todo_data = request.data
        new_todo = Todo.objects.create(name=todo_data['name'], created_date=todo_data['created_date'],
                                       due_on_date=todo_data['due_on_date'], owner=todo_data['owner'],
                                       category=todo_data['category'], list_id=todo_data['list_id'])
        new_todo.save()
        serializer = TodoModelSerializer(new_todo)
        return Response(serializer.data)

    def destroy(self, request):
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            pass
        return Response(status=status.HTTP_204_NO_CONTENT)

    def update(self, request):
        print(request.data['result'])

Lab5_todo/lab5/templates/completed_todos_list.html
{% extends 'index.html' %}
{% block body %}

    <h2>Completed Tasks in "List{{ todo_list.name }}"</h2>
    <div class="todos-list">
        <table class="list">
            <tr>
                <th>Task</th>
                <th>Created</th>
                <th>Due on</th>
                <th>Owner</th>
                <th>Mark</th>
            </tr>
            {% for todo in todos %}
            <tr>
                <td>{{ todo.name }}</td>
                <td>{{ todo.created_date }}</td>
                <td>{{ todo.due_on_date }}</td>
                <td>{{ todo.owner }}</td>
                <td><button class="mark">Done</button></td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div id="buttons">
        <button class="view">View incomplete tasks</button>
        <button class="delete">Delete this list</button>
    </div>
{% endblock %}

Lab5_todo/lab5/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To Do List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
</head>
<body>
    <header>
        <h3>BFDjango TODO</h3>
    </header>

    <div id="add_task">
        <button id="add">Add Task</button>
    </div>

    {% block body %}

    {% endblock %}



</body>
</html>

Lab5_todo/lab5/templates/todos_list.html
{% extends 'index.html' %}
{% block body %}
    <h2>Tasks in "List {{ todo_list.name }}"</h2>
    <div class="todos-list">
        <table class="list">
            <tr>
                <th>Task</th>
                <th>Created</th>
                <th>Due on</th>
                <th>Owner</th>
                <th>Mark</th>
            </tr>
            {% for todo in todos %}
            <tr>
                <td>{{ todo.name }}</td>
                <td>{{ todo.created_date }}</td>
                <td>{{ todo.due_on_date }}</td>
                <td>{{ todo.owner }}</td>
                {% if todo.category == 'Incomplete' %}
                <td><button class="mark">Not Done</button>
                </td>
                    {% else %}
                    <td><button class="mark">Done</button>
                    </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
    <div id="buttons">
        <button class="view">View completed tasks</button>
        <button class="delete">Delete this list</button>
    </div>

{% endblock %}